create table if not exists public.listing_fee_adjustments (
    adjustment_id bigint generated by default as identity primary key,
    character_id uuid not null,
    listing_id bigint not null,
    item_name text not null,
    category_name text,
    market_stall_name text,
    quantity numeric not null,
    old_total_price numeric not null,
    new_total_price numeric not null,
    fee numeric not null check (fee > 0),
    created_at timestamptz not null default now()
);

alter table public.listing_fee_adjustments enable row level security;

drop policy if exists "Users can view their listing fee adjustments" on public.listing_fee_adjustments;
create policy "Users can view their listing fee adjustments"
on public.listing_fee_adjustments for select
using (
    exists (
        select 1 from public.characters c
        where c.character_id = listing_fee_adjustments.character_id
          and c.user_id = auth.uid()
    )
);

drop policy if exists "Users can delete their listing fee adjustments" on public.listing_fee_adjustments;
create policy "Users can delete their listing fee adjustments"
on public.listing_fee_adjustments for delete
using (
    exists (
        select 1 from public.characters c
        where c.character_id = listing_fee_adjustments.character_id
          and c.user_id = auth.uid()
    )
);

create or replace function public.apply_bulk_listing_price_update(
    p_character_id uuid,
    p_listing_ids bigint[],
    p_new_total_price numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_listing record;
    v_current_gold numeric;
    v_total_fee numeric := 0;
    v_additional_fee numeric;
    v_new_fee numeric;
    v_updated_count integer := 0;
begin
    if p_new_total_price is null or p_new_total_price <= 0 then
        raise exception 'Price must be greater than zero.';
    end if;

    if coalesce(array_length(p_listing_ids, 1), 0) = 0 then
        raise exception 'No listings were selected.';
    end if;

    if not exists (
        select 1 from public.characters
        where character_id = p_character_id and user_id = auth.uid()
    ) then
        raise exception 'Character not found or access denied.';
    end if;

    select gold into v_current_gold
    from public.characters
    where character_id = p_character_id
    for update;

    for v_listing in
        select
            ml.listing_id,
            ml.item_id,
            ml.market_stall_id,
            ml.quantity_listed,
            ml.total_listed_price,
            coalesce(ml.market_fee, 0) as market_fee,
            coalesce(i.item_name, 'Unknown Item') as item_name,
            ic.category_name,
            ms.stall_name
        from public.market_listings ml
        left join public.items i on i.item_id = ml.item_id
        left join public.item_categories ic on ic.category_id = i.category_id
        left join public.market_stalls ms on ms.id = ml.market_stall_id
        where ml.character_id = p_character_id
          and ml.listing_id = any(p_listing_ids)
          and ml.is_cancelled = false
          and ml.is_fully_sold = false
        for update of ml
    loop
        v_new_fee := v_listing.market_fee;
        v_additional_fee := 0;

        if p_new_total_price > v_listing.total_listed_price then
            v_new_fee := greatest(ceil(p_new_total_price * 0.05), v_listing.market_fee);
            v_additional_fee := v_new_fee - v_listing.market_fee;
        end if;

        v_total_fee := v_total_fee + v_additional_fee;

        update public.market_listings
        set total_listed_price = p_new_total_price,
            listed_price_per_unit = p_new_total_price / nullif(v_listing.quantity_listed, 0),
            market_fee = v_new_fee
        where listing_id = v_listing.listing_id
          and character_id = p_character_id;

        if v_additional_fee > 0 then
            insert into public.listing_fee_adjustments (
                character_id, listing_id, item_name, category_name, market_stall_name,
                quantity, old_total_price, new_total_price, fee
            ) values (
                p_character_id, v_listing.listing_id, v_listing.item_name,
                v_listing.category_name, v_listing.stall_name, v_listing.quantity_listed,
                v_listing.total_listed_price, p_new_total_price, v_additional_fee
            );
        end if;

        v_updated_count := v_updated_count + 1;
    end loop;

    if v_updated_count <> array_length(p_listing_ids, 1) then
        raise exception 'One or more listings were unavailable. No changes were applied.';
    end if;

    if coalesce(v_current_gold, 0) < v_total_fee then
        raise exception 'Not enough gold. Need %g but only have %g.', v_total_fee, coalesce(v_current_gold, 0);
    end if;

    update public.characters
    set gold = coalesce(v_current_gold, 0) - v_total_fee
    where character_id = p_character_id;

    return jsonb_build_object(
        'updated_count', v_updated_count,
        'additional_fee', v_total_fee,
        'new_gold', coalesce(v_current_gold, 0) - v_total_fee
    );
end;
$$;

revoke all on function public.apply_bulk_listing_price_update(uuid, bigint[], numeric) from public;
grant select, delete on public.listing_fee_adjustments to authenticated;
grant usage, select on sequence public.listing_fee_adjustments_adjustment_id_seq to authenticated;
grant execute on function public.apply_bulk_listing_price_update(uuid, bigint[], numeric) to authenticated;

notify pgrst, 'reload schema';
